// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_blink_arrive :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.2713))
	out := make([]f32, frames * 2)
	defer delete(out)

	rush: ma.noise
	rush_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)
	if ma.noise_init(&rush_cfg, nil, &rush) != .SUCCESS {
		return
	}
	defer ma.noise_uninit(&rush, nil)
	rush_buf := make([]f32, frames)
	defer delete(rush_buf)
	read_noise_window(&rush, rush_buf, sr, 0, f32(0.16))

	drop: ma.waveform
	drop_f0 := f32(280) * (f32(0.94) + rand.float32() * f32(0.12))
	drop_f1 := max(f32(0.001), f32(70) * (f32(0.94) + rand.float32() * f32(0.12)))
	drop_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(drop_f0))
	if ma.waveform_init(&drop_cfg, &drop) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&drop)
	drop_buf := make([]f32, frames)
	defer delete(drop_buf)
	read_waveform_ramp(&drop, drop_buf, sr, drop_f0, drop_f1, f32(0.02), f32(0.16), .exp)

	rushBp: ma.biquad
	rushBp_f0 := f32(520) * (f32(0.95) + rand.float32() * f32(0.1))
	rushBp_f1 := max(f32(0.001), f32(2400) * (f32(0.95) + rand.float32() * f32(0.1)))
	if !biquad_init_rbj(&rushBp, sr, .bandpass, rushBp_f0, f32(2)) {
		return
	}
	defer ma.biquad_uninit(&rushBp, nil)
	rushBp_buf := make([]f32, frames)
	defer delete(rushBp_buf)
	biquad_sweep(&rushBp, rush_buf, rushBp_buf, sr, .bandpass, f32(2), rushBp_f0, rushBp_f1, f32(0.12))

	rushAmp_peak := max(f32(0.001), f32(0.16) * (f32(0.95) + rand.float32() * f32(0.1)))
	rushAmp_buf := make([]f32, frames)
	defer delete(rushAmp_buf)
	gain_env(rushBp_buf, rushAmp_buf, sr, rushAmp_peak, 0, f32(0.16))

	toss_buf := make([]f32, frames * 2)
	defer delete(toss_buf)
	pan_to_stereo(rushAmp_buf, toss_buf, f32(0.3))

	dropAmp_peak := max(f32(0.001), f32(0.14) * (f32(0.94) + rand.float32() * f32(0.12)))
	dropAmp_buf := make([]f32, frames)
	defer delete(dropAmp_buf)
	gain_env(drop_buf, dropAmp_buf, sr, dropAmp_peak, f32(0.02), f32(0.16))

	space_buf := make([]f32, frames)
	defer delete(space_buf)
	delay_line(dropAmp_buf, space_buf, sr, f32(0.055), f32(0.34), f32(0.22))

	add_stereo(out, toss_buf)
	add_mono_to_stereo(out, space_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
read_noise_window :: proc(src: ^ma.noise, out: []f32, sr: u32, start, stop: f32) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	ma.noise_read_pcm_frames(src, raw_data(out[i0:i1]), u64(i1 - i0), nil)
}

@(private="file")
Biquad_Kind :: enum {
	lowpass,
	highpass,
	bandpass,
	notch,
}

@(private="file")
rbj_config :: proc(sr: u32, kind: Biquad_Kind, freq, q: f32) -> ma.biquad_config {
	f := clamp(freq, 10, f32(sr) * 0.45)
	w := math.TAU * f / f32(sr)
	sin_w := math.sin(w)
	cos_w := math.cos(w)
	qq := max(q, 0.0001)
	alpha := sin_w / (2 * qq)
	b0, b1, b2, a0, a1, a2: f32
	switch kind {
	case .lowpass:
		b0 = (1 - cos_w) * 0.5
		b1 = 1 - cos_w
		b2 = (1 - cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .highpass:
		b0 = (1 + cos_w) * 0.5
		b1 = -(1 + cos_w)
		b2 = (1 + cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .bandpass:
		b0 = alpha
		b1 = 0
		b2 = -alpha
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .notch:
		b0 = 1
		b1 = -2 * cos_w
		b2 = 1
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	}
	return ma.biquad_config_init(.f32, 1, f64(b0 / a0), f64(b1 / a0), f64(b2 / a0), 1, f64(a1 / a0), f64(a2 / a0))
}

@(private="file")
biquad_init_rbj :: proc(bq: ^ma.biquad, sr: u32, kind: Biquad_Kind, freq, q: f32) -> bool {
	cfg := rbj_config(sr, kind, freq, q)
	return ma.biquad_init(&cfg, nil, bq) == .SUCCESS
}

@(private="file")
biquad_sweep :: proc(bq: ^ma.biquad, in_buf, out_buf: []f32, sr: u32, kind: Biquad_Kind, q, f0, f1, ramp_time: f32) {
	n := min(len(in_buf), len(out_buf))
	last := f0
	cfg := rbj_config(sr, kind, f0, q)
	ma.biquad_reinit(&cfg, bq)
	for i in 0 ..< n {
		f := f0
		if ramp_time > 0 && f1 != f0 {
			x := clamp((f32(i) / f32(sr)) / ramp_time, 0, 1)
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		}
		if abs(f - last) > 0.5 {
			cfg = rbj_config(sr, kind, f, q)
			ma.biquad_reinit(&cfg, bq)
			last = f
		}
		x := in_buf[i]
		ma.biquad_process_pcm_frames(bq, &out_buf[i], &x, 1)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
pan_to_stereo :: proc(in_buf, out_buf: []f32, pan: f32) {
	angle := (pan + 1) * (math.PI * 0.25)
	l := math.cos(angle)
	r := math.sin(angle)
	n := min(len(in_buf), len(out_buf) / 2)
	for i in 0 ..< n {
		out_buf[i * 2] = in_buf[i] * l
		out_buf[i * 2 + 1] = in_buf[i] * r
	}
}

@(private="file")
delay_line :: proc(in_buf, out_buf: []f32, sr: u32, time, mix, feedback: f32) {
	n := min(len(in_buf), len(out_buf))
	buf_len := int(math.ceil_f64(f64(sr) * f64(time))) + 1
	delay_buf := make([]f32, buf_len)
	defer delete(delay_buf)
	pos := 0
	for i in 0 ..< n {
		tap := delay_buf[pos]
		delay_buf[pos] = in_buf[i] + tap * feedback
		pos = (pos + 1) % buf_len
		out_buf[i] = in_buf[i] * (1 - mix) + tap * mix
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}

@(private="file")
add_stereo :: proc(out, stereo: []f32) {
	n := min(len(out), len(stereo))
	for i in 0 ..< n {
		out[i] += stereo[i]
	}
}
