// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_heal_loop :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.23))
	out := make([]f32, frames * 2)
	defer delete(out)

	root: ma.waveform
	root_f0 := f32(523) * (f32(0.98) + rand.float32() * f32(0.04))
	root_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(root_f0))
	if ma.waveform_init(&root_cfg, &root) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&root)
	root_buf := make([]f32, frames)
	defer delete(root_buf)
	read_waveform_ramp(&root, root_buf, sr, root_f0, root_f0, 0, f32(0.2), .exp)

	fifth: ma.waveform
	fifth_f0 := f32(784) * (f32(0.97) + rand.float32() * f32(0.06))
	fifth_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(fifth_f0))
	if ma.waveform_init(&fifth_cfg, &fifth) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&fifth)
	fifth_buf := make([]f32, frames)
	defer delete(fifth_buf)
	read_waveform_ramp(&fifth, fifth_buf, sr, fifth_f0, fifth_f0, f32(0.03), f32(0.21), .exp)

	dust: ma.noise
	dust_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)
	if ma.noise_init(&dust_cfg, nil, &dust) != .SUCCESS {
		return
	}
	defer ma.noise_uninit(&dust, nil)
	dust_buf := make([]f32, frames)
	defer delete(dust_buf)
	read_noise_window(&dust, dust_buf, sr, f32(0.04), f32(0.12))

	rootAmp_peak := max(f32(0.001), f32(0.09) * (f32(0.97) + rand.float32() * f32(0.06)))
	rootAmp_buf := make([]f32, frames)
	defer delete(rootAmp_buf)
	gain_env(root_buf, rootAmp_buf, sr, rootAmp_peak, 0, f32(0.2))

	fifthAmp_peak := max(f32(0.001), f32(0.07) * (f32(0.96) + rand.float32() * f32(0.08)))
	fifthAmp_buf := make([]f32, frames)
	defer delete(fifthAmp_buf)
	gain_env(fifth_buf, fifthAmp_buf, sr, fifthAmp_peak, f32(0.03), f32(0.21))

	dustBp: ma.biquad
	dustBp_f0 := f32(4800) * (f32(0.95) + rand.float32() * f32(0.1))
	dustBp_f1 := max(f32(0.001), f32(6200) * (f32(0.95) + rand.float32() * f32(0.1)))
	if !biquad_init_rbj(&dustBp, sr, .bandpass, dustBp_f0, f32(3.2)) {
		return
	}
	defer ma.biquad_uninit(&dustBp, nil)
	dustBp_buf := make([]f32, frames)
	defer delete(dustBp_buf)
	biquad_sweep(&dustBp, dust_buf, dustBp_buf, sr, .bandpass, f32(3.2), dustBp_f0, dustBp_f1, f32(0.06))

	dustAmp_peak := max(f32(0.001), f32(0.035) * (f32(0.92) + rand.float32() * f32(0.16)))
	dustAmp_buf := make([]f32, frames)
	defer delete(dustAmp_buf)
	gain_env(dustBp_buf, dustAmp_buf, sr, dustAmp_peak, f32(0.04), f32(0.12))

	add_mono_to_stereo(out, rootAmp_buf)
	add_mono_to_stereo(out, fifthAmp_buf)
	add_mono_to_stereo(out, dustAmp_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
read_noise_window :: proc(src: ^ma.noise, out: []f32, sr: u32, start, stop: f32) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	ma.noise_read_pcm_frames(src, raw_data(out[i0:i1]), u64(i1 - i0), nil)
}

@(private="file")
Biquad_Kind :: enum {
	lowpass,
	highpass,
	bandpass,
	notch,
}

@(private="file")
rbj_config :: proc(sr: u32, kind: Biquad_Kind, freq, q: f32) -> ma.biquad_config {
	f := clamp(freq, 10, f32(sr) * 0.45)
	w := math.TAU * f / f32(sr)
	sin_w := math.sin(w)
	cos_w := math.cos(w)
	qq := max(q, 0.0001)
	alpha := sin_w / (2 * qq)
	b0, b1, b2, a0, a1, a2: f32
	switch kind {
	case .lowpass:
		b0 = (1 - cos_w) * 0.5
		b1 = 1 - cos_w
		b2 = (1 - cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .highpass:
		b0 = (1 + cos_w) * 0.5
		b1 = -(1 + cos_w)
		b2 = (1 + cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .bandpass:
		b0 = alpha
		b1 = 0
		b2 = -alpha
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .notch:
		b0 = 1
		b1 = -2 * cos_w
		b2 = 1
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	}
	return ma.biquad_config_init(.f32, 1, f64(b0 / a0), f64(b1 / a0), f64(b2 / a0), 1, f64(a1 / a0), f64(a2 / a0))
}

@(private="file")
biquad_init_rbj :: proc(bq: ^ma.biquad, sr: u32, kind: Biquad_Kind, freq, q: f32) -> bool {
	cfg := rbj_config(sr, kind, freq, q)
	return ma.biquad_init(&cfg, nil, bq) == .SUCCESS
}

@(private="file")
biquad_sweep :: proc(bq: ^ma.biquad, in_buf, out_buf: []f32, sr: u32, kind: Biquad_Kind, q, f0, f1, ramp_time: f32) {
	n := min(len(in_buf), len(out_buf))
	last := f0
	cfg := rbj_config(sr, kind, f0, q)
	ma.biquad_reinit(&cfg, bq)
	for i in 0 ..< n {
		f := f0
		if ramp_time > 0 && f1 != f0 {
			x := clamp((f32(i) / f32(sr)) / ramp_time, 0, 1)
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		}
		if abs(f - last) > 0.5 {
			cfg = rbj_config(sr, kind, f, q)
			ma.biquad_reinit(&cfg, bq)
			last = f
		}
		x := in_buf[i]
		ma.biquad_process_pcm_frames(bq, &out_buf[i], &x, 1)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}
