// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_kill :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.22))
	out := make([]f32, frames * 2)
	defer delete(out)

	stabA: ma.waveform
	stabA_f0 := f32(880) * (f32(0.97) + rand.float32() * f32(0.06))
	stabA_cfg := ma.waveform_config_init(.f32, 1, sr, .square, 1, f64(stabA_f0))
	if ma.waveform_init(&stabA_cfg, &stabA) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&stabA)
	stabA_buf := make([]f32, frames)
	defer delete(stabA_buf)
	read_waveform_ramp(&stabA, stabA_buf, sr, stabA_f0, stabA_f0, 0, f32(0.04), .exp)

	stabB: ma.waveform
	stabB_f0 := f32(1320) * (f32(0.97) + rand.float32() * f32(0.06))
	stabB_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(stabB_f0))
	if ma.waveform_init(&stabB_cfg, &stabB) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&stabB)
	stabB_buf := make([]f32, frames)
	defer delete(stabB_buf)
	read_waveform_ramp(&stabB, stabB_buf, sr, stabB_f0, stabB_f0, f32(0.04), f32(0.12), .exp)

	stabC: ma.waveform
	stabC_f0 := f32(1760) * (f32(0.97) + rand.float32() * f32(0.06))
	stabC_f1 := f32(2200) * (f32(0.97) + rand.float32() * f32(0.06))
	stabC_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(stabC_f0))
	if ma.waveform_init(&stabC_cfg, &stabC) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&stabC)
	stabC_buf := make([]f32, frames)
	defer delete(stabC_buf)
	read_waveform_ramp(&stabC, stabC_buf, sr, stabC_f0, stabC_f1, f32(0.08), f32(0.2), .lin)

	stabAAmp_peak := max(f32(0.001), f32(0.12) * (f32(0.96) + rand.float32() * f32(0.08)))
	stabAAmp_buf := make([]f32, frames)
	defer delete(stabAAmp_buf)
	gain_env(stabA_buf, stabAAmp_buf, sr, stabAAmp_peak, 0, f32(0.04))

	stabBAmp_peak := max(f32(0.001), f32(0.14) * (f32(0.96) + rand.float32() * f32(0.08)))
	stabBAmp_buf := make([]f32, frames)
	defer delete(stabBAmp_buf)
	gain_env(stabB_buf, stabBAmp_buf, sr, stabBAmp_peak, f32(0.04), f32(0.12))

	stabCAmp_peak := max(f32(0.001), f32(0.12) * (f32(0.96) + rand.float32() * f32(0.08)))
	stabCAmp_buf := make([]f32, frames)
	defer delete(stabCAmp_buf)
	gain_env(stabC_buf, stabCAmp_buf, sr, stabCAmp_peak, f32(0.08), f32(0.2))

	add_mono_to_stereo(out, stabAAmp_buf)
	add_mono_to_stereo(out, stabBAmp_buf)
	add_mono_to_stereo(out, stabCAmp_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}
