// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_lance_charge :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.14))
	out := make([]f32, frames * 2)
	defer delete(out)

	crystal: ma.waveform
	crystal_f0 := f32(1760) * (f32(0.96) + rand.float32() * f32(0.08))
	crystal_f1 := f32(2480) * (f32(0.96) + rand.float32() * f32(0.08))
	crystal_cfg := ma.waveform_config_init(.f32, 1, sr, .triangle, 1, f64(crystal_f0))
	if ma.waveform_init(&crystal_cfg, &crystal) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&crystal)
	crystal_buf := make([]f32, frames)
	defer delete(crystal_buf)
	read_waveform_ramp(&crystal, crystal_buf, sr, crystal_f0, crystal_f1, 0, f32(0.12), .lin)

	scrape: ma.noise
	scrape_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)
	if ma.noise_init(&scrape_cfg, nil, &scrape) != .SUCCESS {
		return
	}
	defer ma.noise_uninit(&scrape, nil)
	scrape_buf := make([]f32, frames)
	defer delete(scrape_buf)
	read_noise_window(&scrape, scrape_buf, sr, 0, f32(0.09))

	ping: ma.waveform
	ping_f0 := f32(3100) * (f32(0.94) + rand.float32() * f32(0.12))
	ping_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(ping_f0))
	if ma.waveform_init(&ping_cfg, &ping) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&ping)
	ping_buf := make([]f32, frames)
	defer delete(ping_buf)
	read_waveform_ramp(&ping, ping_buf, sr, ping_f0, ping_f0, f32(0.03), f32(0.07), .exp)

	crystalAmp_peak := max(f32(0.001), f32(0.09) * (f32(0.95) + rand.float32() * f32(0.1)))
	crystalAmp_buf := make([]f32, frames)
	defer delete(crystalAmp_buf)
	gain_env(crystal_buf, crystalAmp_buf, sr, crystalAmp_peak, 0, f32(0.12))

	scrapeHp: ma.biquad
	scrapeHp_f0 := f32(6200)
	if !biquad_init_rbj(&scrapeHp, sr, .highpass, scrapeHp_f0, f32(0.8)) {
		return
	}
	defer ma.biquad_uninit(&scrapeHp, nil)
	scrapeHp_buf := make([]f32, frames)
	defer delete(scrapeHp_buf)
	biquad_sweep(&scrapeHp, scrape_buf, scrapeHp_buf, sr, .highpass, f32(0.8), scrapeHp_f0, scrapeHp_f0, 0)

	scrapeAmp_peak := max(f32(0.001), f32(0.06) * (f32(0.92) + rand.float32() * f32(0.16)))
	scrapeAmp_buf := make([]f32, frames)
	defer delete(scrapeAmp_buf)
	gain_env(scrapeHp_buf, scrapeAmp_buf, sr, scrapeAmp_peak, 0, f32(0.09))

	pingBp: ma.biquad
	pingBp_f0 := f32(3100) * (f32(0.95) + rand.float32() * f32(0.1))
	pingBp_f1 := max(f32(0.001), f32(3600) * (f32(0.95) + rand.float32() * f32(0.1)))
	if !biquad_init_rbj(&pingBp, sr, .bandpass, pingBp_f0, f32(8)) {
		return
	}
	defer ma.biquad_uninit(&pingBp, nil)
	pingBp_buf := make([]f32, frames)
	defer delete(pingBp_buf)
	biquad_sweep(&pingBp, ping_buf, pingBp_buf, sr, .bandpass, f32(8), pingBp_f0, pingBp_f1, f32(0.03))

	pingAmp_peak := max(f32(0.001), f32(0.05) * (f32(0.92) + rand.float32() * f32(0.16)))
	pingAmp_buf := make([]f32, frames)
	defer delete(pingAmp_buf)
	gain_env(pingBp_buf, pingAmp_buf, sr, pingAmp_peak, f32(0.03), f32(0.07))

	add_mono_to_stereo(out, crystalAmp_buf)
	add_mono_to_stereo(out, scrapeAmp_buf)
	add_mono_to_stereo(out, pingAmp_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
read_noise_window :: proc(src: ^ma.noise, out: []f32, sr: u32, start, stop: f32) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	ma.noise_read_pcm_frames(src, raw_data(out[i0:i1]), u64(i1 - i0), nil)
}

@(private="file")
Biquad_Kind :: enum {
	lowpass,
	highpass,
	bandpass,
	notch,
}

@(private="file")
rbj_config :: proc(sr: u32, kind: Biquad_Kind, freq, q: f32) -> ma.biquad_config {
	f := clamp(freq, 10, f32(sr) * 0.45)
	w := math.TAU * f / f32(sr)
	sin_w := math.sin(w)
	cos_w := math.cos(w)
	qq := max(q, 0.0001)
	alpha := sin_w / (2 * qq)
	b0, b1, b2, a0, a1, a2: f32
	switch kind {
	case .lowpass:
		b0 = (1 - cos_w) * 0.5
		b1 = 1 - cos_w
		b2 = (1 - cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .highpass:
		b0 = (1 + cos_w) * 0.5
		b1 = -(1 + cos_w)
		b2 = (1 + cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .bandpass:
		b0 = alpha
		b1 = 0
		b2 = -alpha
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .notch:
		b0 = 1
		b1 = -2 * cos_w
		b2 = 1
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	}
	return ma.biquad_config_init(.f32, 1, f64(b0 / a0), f64(b1 / a0), f64(b2 / a0), 1, f64(a1 / a0), f64(a2 / a0))
}

@(private="file")
biquad_init_rbj :: proc(bq: ^ma.biquad, sr: u32, kind: Biquad_Kind, freq, q: f32) -> bool {
	cfg := rbj_config(sr, kind, freq, q)
	return ma.biquad_init(&cfg, nil, bq) == .SUCCESS
}

@(private="file")
biquad_sweep :: proc(bq: ^ma.biquad, in_buf, out_buf: []f32, sr: u32, kind: Biquad_Kind, q, f0, f1, ramp_time: f32) {
	n := min(len(in_buf), len(out_buf))
	last := f0
	cfg := rbj_config(sr, kind, f0, q)
	ma.biquad_reinit(&cfg, bq)
	for i in 0 ..< n {
		f := f0
		if ramp_time > 0 && f1 != f0 {
			x := clamp((f32(i) / f32(sr)) / ramp_time, 0, 1)
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		}
		if abs(f - last) > 0.5 {
			cfg = rbj_config(sr, kind, f, q)
			ma.biquad_reinit(&cfg, bq)
			last = f
		}
		x := in_buf[i]
		ma.biquad_process_pcm_frames(bq, &out_buf[i], &x, 1)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}

@(private="file")
MAX_PLAYING :: 8

@(private="file")
Playing :: struct {
	used:   bool,
	buffer: ma.audio_buffer,
	sound:  ma.sound,
}

@(private="file")
g_playing: [MAX_PLAYING]Playing

@(private="file")
reap_playing :: proc() {
	for &slot in g_playing {
		if slot.used && bool(ma.sound_at_end(&slot.sound)) {
			ma.sound_uninit(&slot.sound)
			ma.audio_buffer_uninit(&slot.buffer)
			slot.used = false
		}
	}
}

@(private="file")
submit_pcm :: proc(engine: ^ma.engine, frames: []f32, sr: u32) {
	if engine == nil || len(frames) < 2 {
		return
	}
	reap_playing()
	slot: ^Playing
	for &s in g_playing {
		if !s.used {
			slot = &s
			break
		}
	}
	if slot == nil {
		slot = &g_playing[0]
		ma.sound_uninit(&slot.sound)
		ma.audio_buffer_uninit(&slot.buffer)
		slot.used = false
	}
	nframes := u64(len(frames) / 2)
	cfg := ma.audio_buffer_config_init(.f32, 2, nframes, raw_data(frames), nil)
	cfg.sampleRate = sr
	if ma.audio_buffer_init_copy(&cfg, &slot.buffer) != .SUCCESS {
		return
	}
	flags := ma.sound_flags{.NO_PITCH, .NO_SPATIALIZATION}
	if ma.sound_init_from_data_source(engine, cast(^ma.data_source)&slot.buffer, flags, nil, &slot.sound) != .SUCCESS {
		ma.audio_buffer_uninit(&slot.buffer)
		return
	}
	if ma.sound_start(&slot.sound) != .SUCCESS {
		ma.sound_uninit(&slot.sound)
		ma.audio_buffer_uninit(&slot.buffer)
		return
	}
	slot.used = true
}
