// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_lance_impact :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.11))
	out := make([]f32, frames * 2)
	defer delete(out)

	shardA: ma.waveform
	shardA_f0 := f32(2200) * (f32(0.92) + rand.float32() * f32(0.16))
	shardA_f1 := max(f32(0.001), f32(700) * (f32(0.92) + rand.float32() * f32(0.16)))
	shardA_cfg := ma.waveform_config_init(.f32, 1, sr, .triangle, 1, f64(shardA_f0))
	if ma.waveform_init(&shardA_cfg, &shardA) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&shardA)
	shardA_buf := make([]f32, frames)
	defer delete(shardA_buf)
	read_waveform_ramp(&shardA, shardA_buf, sr, shardA_f0, shardA_f1, 0, f32(0.05), .exp)

	shardB: ma.waveform
	shardB_f0 := f32(1540) * (f32(0.92) + rand.float32() * f32(0.16))
	shardB_f1 := max(f32(0.001), f32(480) * (f32(0.92) + rand.float32() * f32(0.16)))
	shardB_cfg := ma.waveform_config_init(.f32, 1, sr, .triangle, 1, f64(shardB_f0))
	if ma.waveform_init(&shardB_cfg, &shardB) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&shardB)
	shardB_buf := make([]f32, frames)
	defer delete(shardB_buf)
	read_waveform_ramp(&shardB, shardB_buf, sr, shardB_f0, shardB_f1, f32(0.008), f32(0.068), .exp)

	shardC: ma.waveform
	shardC_f0 := f32(2860) * (f32(0.9) + rand.float32() * f32(0.2))
	shardC_f1 := max(f32(0.001), f32(900) * (f32(0.9) + rand.float32() * f32(0.2)))
	shardC_cfg := ma.waveform_config_init(.f32, 1, sr, .triangle, 1, f64(shardC_f0))
	if ma.waveform_init(&shardC_cfg, &shardC) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&shardC)
	shardC_buf := make([]f32, frames)
	defer delete(shardC_buf)
	read_waveform_ramp(&shardC, shardC_buf, sr, shardC_f0, shardC_f1, f32(0.016), f32(0.056), .exp)

	shatter: ma.noise
	shatter_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)
	if ma.noise_init(&shatter_cfg, nil, &shatter) != .SUCCESS {
		return
	}
	defer ma.noise_uninit(&shatter, nil)
	shatter_buf := make([]f32, frames)
	defer delete(shatter_buf)
	read_noise_window(&shatter, shatter_buf, sr, 0, f32(0.045))

	body: ma.waveform
	body_f0 := f32(150) * (f32(0.93) + rand.float32() * f32(0.14))
	body_f1 := max(f32(0.001), f32(55) * (f32(0.93) + rand.float32() * f32(0.14)))
	body_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(body_f0))
	if ma.waveform_init(&body_cfg, &body) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&body)
	body_buf := make([]f32, frames)
	defer delete(body_buf)
	read_waveform_ramp(&body, body_buf, sr, body_f0, body_f1, 0, f32(0.09), .exp)

	shardAAmp_peak := max(f32(0.001), f32(0.11) * (f32(0.92) + rand.float32() * f32(0.16)))
	shardAAmp_buf := make([]f32, frames)
	defer delete(shardAAmp_buf)
	gain_env(shardA_buf, shardAAmp_buf, sr, shardAAmp_peak, 0, f32(0.05))

	shardBAmp_peak := max(f32(0.001), f32(0.09) * (f32(0.92) + rand.float32() * f32(0.16)))
	shardBAmp_buf := make([]f32, frames)
	defer delete(shardBAmp_buf)
	gain_env(shardB_buf, shardBAmp_buf, sr, shardBAmp_peak, f32(0.008), f32(0.068))

	shardCAmp_peak := max(f32(0.001), f32(0.07) * (f32(0.9) + rand.float32() * f32(0.2)))
	shardCAmp_buf := make([]f32, frames)
	defer delete(shardCAmp_buf)
	gain_env(shardC_buf, shardCAmp_buf, sr, shardCAmp_peak, f32(0.016), f32(0.056))

	shatterBp: ma.biquad
	shatterBp_f0 := f32(4100) * (f32(0.92) + rand.float32() * f32(0.16))
	shatterBp_f1 := max(f32(0.001), f32(1100) * (f32(0.92) + rand.float32() * f32(0.16)))
	if !biquad_init_rbj(&shatterBp, sr, .bandpass, shatterBp_f0, f32(2.4)) {
		return
	}
	defer ma.biquad_uninit(&shatterBp, nil)
	shatterBp_buf := make([]f32, frames)
	defer delete(shatterBp_buf)
	biquad_sweep(&shatterBp, shatter_buf, shatterBp_buf, sr, .bandpass, f32(2.4), shatterBp_f0, shatterBp_f1, f32(0.035))

	shatterAmp_peak := max(f32(0.001), f32(0.12) * (f32(0.92) + rand.float32() * f32(0.16)))
	shatterAmp_buf := make([]f32, frames)
	defer delete(shatterAmp_buf)
	gain_env(shatterBp_buf, shatterAmp_buf, sr, shatterAmp_peak, 0, f32(0.045))

	bodyAmp_peak := max(f32(0.001), f32(0.14) * (f32(0.94) + rand.float32() * f32(0.12)))
	bodyAmp_buf := make([]f32, frames)
	defer delete(bodyAmp_buf)
	gain_env(body_buf, bodyAmp_buf, sr, bodyAmp_peak, 0, f32(0.09))

	add_mono_to_stereo(out, shardAAmp_buf)
	add_mono_to_stereo(out, shardBAmp_buf)
	add_mono_to_stereo(out, shardCAmp_buf)
	add_mono_to_stereo(out, shatterAmp_buf)
	add_mono_to_stereo(out, bodyAmp_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
read_noise_window :: proc(src: ^ma.noise, out: []f32, sr: u32, start, stop: f32) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	ma.noise_read_pcm_frames(src, raw_data(out[i0:i1]), u64(i1 - i0), nil)
}

@(private="file")
Biquad_Kind :: enum {
	lowpass,
	highpass,
	bandpass,
	notch,
}

@(private="file")
rbj_config :: proc(sr: u32, kind: Biquad_Kind, freq, q: f32) -> ma.biquad_config {
	f := clamp(freq, 10, f32(sr) * 0.45)
	w := math.TAU * f / f32(sr)
	sin_w := math.sin(w)
	cos_w := math.cos(w)
	qq := max(q, 0.0001)
	alpha := sin_w / (2 * qq)
	b0, b1, b2, a0, a1, a2: f32
	switch kind {
	case .lowpass:
		b0 = (1 - cos_w) * 0.5
		b1 = 1 - cos_w
		b2 = (1 - cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .highpass:
		b0 = (1 + cos_w) * 0.5
		b1 = -(1 + cos_w)
		b2 = (1 + cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .bandpass:
		b0 = alpha
		b1 = 0
		b2 = -alpha
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .notch:
		b0 = 1
		b1 = -2 * cos_w
		b2 = 1
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	}
	return ma.biquad_config_init(.f32, 1, f64(b0 / a0), f64(b1 / a0), f64(b2 / a0), 1, f64(a1 / a0), f64(a2 / a0))
}

@(private="file")
biquad_init_rbj :: proc(bq: ^ma.biquad, sr: u32, kind: Biquad_Kind, freq, q: f32) -> bool {
	cfg := rbj_config(sr, kind, freq, q)
	return ma.biquad_init(&cfg, nil, bq) == .SUCCESS
}

@(private="file")
biquad_sweep :: proc(bq: ^ma.biquad, in_buf, out_buf: []f32, sr: u32, kind: Biquad_Kind, q, f0, f1, ramp_time: f32) {
	n := min(len(in_buf), len(out_buf))
	last := f0
	cfg := rbj_config(sr, kind, f0, q)
	ma.biquad_reinit(&cfg, bq)
	for i in 0 ..< n {
		f := f0
		if ramp_time > 0 && f1 != f0 {
			x := clamp((f32(i) / f32(sr)) / ramp_time, 0, 1)
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		}
		if abs(f - last) > 0.5 {
			cfg = rbj_config(sr, kind, f, q)
			ma.biquad_reinit(&cfg, bq)
			last = f
		}
		x := in_buf[i]
		ma.biquad_process_pcm_frames(bq, &out_buf[i], &x, 1)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}
