// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sfx

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_orb_cast :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.2878))
	out := make([]f32, frames * 2)
	defer delete(out)

	whoomp: ma.waveform
	whoomp_f0 := f32(88) * (f32(0.95) + rand.float32() * f32(0.1))
	whoomp_f1 := max(f32(0.001), f32(34) * (f32(0.95) + rand.float32() * f32(0.1)))
	whoomp_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(whoomp_f0))
	if ma.waveform_init(&whoomp_cfg, &whoomp) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&whoomp)
	whoomp_buf := make([]f32, frames)
	defer delete(whoomp_buf)
	read_waveform_ramp(&whoomp, whoomp_buf, sr, whoomp_f0, whoomp_f1, 0, f32(0.16), .exp)

	push: ma.noise
	push_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)
	if ma.noise_init(&push_cfg, nil, &push) != .SUCCESS {
		return
	}
	defer ma.noise_uninit(&push, nil)
	push_buf := make([]f32, frames)
	defer delete(push_buf)
	read_noise_window(&push, push_buf, sr, 0, f32(0.1))

	whoompAmp_peak := max(f32(0.001), f32(0.28) * (f32(0.96) + rand.float32() * f32(0.08)))
	whoompAmp_buf := make([]f32, frames)
	defer delete(whoompAmp_buf)
	gain_env(whoomp_buf, whoompAmp_buf, sr, whoompAmp_peak, 0, f32(0.16))

	pushBp: ma.biquad
	pushBp_f0 := f32(620) * (f32(0.92) + rand.float32() * f32(0.16))
	pushBp_f1 := max(f32(0.001), f32(180) * (f32(0.92) + rand.float32() * f32(0.16)))
	if !biquad_init_rbj(&pushBp, sr, .bandpass, pushBp_f0, f32(0.9)) {
		return
	}
	defer ma.biquad_uninit(&pushBp, nil)
	pushBp_buf := make([]f32, frames)
	defer delete(pushBp_buf)
	biquad_sweep(&pushBp, push_buf, pushBp_buf, sr, .bandpass, f32(0.9), pushBp_f0, pushBp_f1, f32(0.08))

	pushDrive_buf := make([]f32, frames)
	defer delete(pushDrive_buf)
	waveshape(pushBp_buf, pushDrive_buf, f32(4))

	pushAmp_peak := max(f32(0.001), f32(0.12) * (f32(0.93) + rand.float32() * f32(0.14)))
	pushAmp_buf := make([]f32, frames)
	defer delete(pushAmp_buf)
	gain_env(pushDrive_buf, pushAmp_buf, sr, pushAmp_peak, 0, f32(0.1))

	slap_buf := make([]f32, frames)
	defer delete(slap_buf)
	delay_line(pushAmp_buf, slap_buf, sr, f32(0.07), f32(0.22), f32(0.18))

	add_mono_to_stereo(out, whoompAmp_buf)
	add_mono_to_stereo(out, slap_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
read_noise_window :: proc(src: ^ma.noise, out: []f32, sr: u32, start, stop: f32) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	ma.noise_read_pcm_frames(src, raw_data(out[i0:i1]), u64(i1 - i0), nil)
}

@(private="file")
Biquad_Kind :: enum {
	lowpass,
	highpass,
	bandpass,
	notch,
}

@(private="file")
rbj_config :: proc(sr: u32, kind: Biquad_Kind, freq, q: f32) -> ma.biquad_config {
	f := clamp(freq, 10, f32(sr) * 0.45)
	w := math.TAU * f / f32(sr)
	sin_w := math.sin(w)
	cos_w := math.cos(w)
	qq := max(q, 0.0001)
	alpha := sin_w / (2 * qq)
	b0, b1, b2, a0, a1, a2: f32
	switch kind {
	case .lowpass:
		b0 = (1 - cos_w) * 0.5
		b1 = 1 - cos_w
		b2 = (1 - cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .highpass:
		b0 = (1 + cos_w) * 0.5
		b1 = -(1 + cos_w)
		b2 = (1 + cos_w) * 0.5
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .bandpass:
		b0 = alpha
		b1 = 0
		b2 = -alpha
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	case .notch:
		b0 = 1
		b1 = -2 * cos_w
		b2 = 1
		a0 = 1 + alpha
		a1 = -2 * cos_w
		a2 = 1 - alpha
	}
	return ma.biquad_config_init(.f32, 1, f64(b0 / a0), f64(b1 / a0), f64(b2 / a0), 1, f64(a1 / a0), f64(a2 / a0))
}

@(private="file")
biquad_init_rbj :: proc(bq: ^ma.biquad, sr: u32, kind: Biquad_Kind, freq, q: f32) -> bool {
	cfg := rbj_config(sr, kind, freq, q)
	return ma.biquad_init(&cfg, nil, bq) == .SUCCESS
}

@(private="file")
biquad_sweep :: proc(bq: ^ma.biquad, in_buf, out_buf: []f32, sr: u32, kind: Biquad_Kind, q, f0, f1, ramp_time: f32) {
	n := min(len(in_buf), len(out_buf))
	last := f0
	cfg := rbj_config(sr, kind, f0, q)
	ma.biquad_reinit(&cfg, bq)
	for i in 0 ..< n {
		f := f0
		if ramp_time > 0 && f1 != f0 {
			x := clamp((f32(i) / f32(sr)) / ramp_time, 0, 1)
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		}
		if abs(f - last) > 0.5 {
			cfg = rbj_config(sr, kind, f, q)
			ma.biquad_reinit(&cfg, bq)
			last = f
		}
		x := in_buf[i]
		ma.biquad_process_pcm_frames(bq, &out_buf[i], &x, 1)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
waveshape :: proc(in_buf, out_buf: []f32, amount: f32) {
	n := min(len(in_buf), len(out_buf))
	for i in 0 ..< n {
		x := clamp(in_buf[i], -1, 1)
		out_buf[i] = ((math.PI + amount) * x) / (math.PI + amount * abs(x))
	}
}

@(private="file")
delay_line :: proc(in_buf, out_buf: []f32, sr: u32, time, mix, feedback: f32) {
	n := min(len(in_buf), len(out_buf))
	buf_len := int(math.ceil_f64(f64(sr) * f64(time))) + 1
	delay_buf := make([]f32, buf_len)
	defer delete(delay_buf)
	pos := 0
	for i in 0 ..< n {
		tap := delay_buf[pos]
		delay_buf[pos] = in_buf[i] + tap * feedback
		pos = (pos + 1) % buf_len
		out_buf[i] = in_buf[i] * (1 - mix) + tap * mix
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}
